Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,6 +20,7 @@ env:
   CUDA_CLUSTER: SH1988
   CI_BUILD_FLAG: "ci_build_flag"
   PYTORCH_COMMIT: ${{ vars.PYTORCH_COMMIT != '' && vars.PYTORCH_COMMIT || 'c263bd43e8e8502d4726643bc6fd046f0130ac0e' }} # pytorch tag 2.0
+  USE_COVERAGE: ${{ github.ref  == "main" && ON || ON }}
 
 concurrency:
   group: ${{ github.head_ref || github.ref }}
@@ -107,14 +108,11 @@ jobs:
         run: |
           ssh ${CAMB_CLUSTER} """
           set -e
-          if [ ${{ github.ref }} == "master" ]; then
-          export USE_COVERAGE=ON
-          fi
           cd ${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/ && cd Build-Camb
           export PYTORCH_DIR=${CAMB_TORCH_BASE_DIR}/${PYTORCH_COMMIT}
           source scripts/ci/camb/ci_camb_env.sh
           srun --job-name=${GITHUB_JOB} --partition=${CAMB_PARTATION} --time=40 --gres=mlu:${MLU_REQUESTS} sh tests/run_camb_tests.sh
-          sh /mnt/lustre/share/platform/dep/sonar/coverage_DIOPI_camb.sh `pwd` ${GITHUB_RUN_NUMBER} || echo "get coverage fail"
+          sh /mnt/lustre/share/platform/dep/sonar/coverage_DIOPI_camb.sh ${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb ${GITHUB_RUN_NUMBER} || echo "get coverage fail"
           """
 
   Test-One-Iter-Camb:
@@ -237,13 +235,10 @@ jobs:
         run: |
           ssh ${CUDA_CLUSTER} """
           set -e
-          if [ ${{ github.ref }} == "master" ]; then
-          export USE_COVERAGE=ON
-          fi
           cd ${CUDA_CI_PATH}/${GITHUB_RUN_NUMBER}/ && cd Build-Cuda
           source scripts/ci/nv/ci_nv_env.sh
           srun --job-name=${GITHUB_RUN_NUMBER}_${GITHUB_JOB} --partition=${CUDA_PARTATION} --gres=gpu:${GPU_REQUESTS} --cpus-per-task=5 --mem=16G --time=70 sh tests/run_nv_tests.sh
-          sh /mnt/cache/share/platform/dep/sonar/coverage_DIPU_nv.sh `pwd` ${GITHUB_RUN_NUMBER} || echo "get coverage fail"
+          bash /mnt/cache/share/platform/dep/sonar/coverage_DIPU_nv.sh ${CUDA_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Cuda ${GITHUB_RUN_NUMBER} || echo "get coverage fail"
           """
   
   Test-One-Iter_Cuda:
