check oneiter

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -170,32 +170,32 @@ jobs:
           rm -rf one_iter_data
           python ../scripts/ci/ci_run_one_iter.py camb ${GITHUB_JOB} "mlu:${MLU_REQUESTS}" \"${CAMB_PARTATION}\" && rm -rf one_iter_data || (rm -rf one_iter_data && exit 1)
           """
-      - name: run-one-iter-for-llm
-        run: |
-          ssh ${CAMB_CLUSTER} """
-          set -ex
-          cd ${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb/dipu
-          export PYTORCH_DIR=${CAMB_TORCH_BASE_DIR}/${PYTORCH_COMMIT}
-          echo "pytorch dir: \${PYTORCH_DIR}"
-          source scripts/ci/camb/ci_camb_env.sh
-          basic_path=${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb/dipu/mmlab_pack
-          source scripts/ci/ci_one_iter.sh export_pythonpath_camb \${basic_path}
-          export PYTHONPATH=\$(pwd):\$PYTHONPATH
-          cd mmlab_pack
-          rm -rf one_iter_data
-          python ../scripts/ci/ci_run_one_iter.py camb ${GITHUB_JOB} "mlu:${MLU_REQUESTS}" \"${CAMB_PARTATION}\" "llm" && rm -rf one_iter_data || (rm -rf one_iter_data && exit 1)
-          """
-      - name: Perform cleanup one iter data
-        if: always()
-        run: |
-          ssh ${CAMB_CLUSTER} """
-              set -ex
-              echo "${GITHUB_RUN_NUMBER}_${GITHUB_JOB}"
-              scancel -n "${GITHUB_RUN_NUMBER}_${GITHUB_JOB}"
-              cd ${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb/dipu/mmlab_pack
-              rm -rf one_iter_data
-              touch one_iter_data # 用于占位，防止创建新的 one_iter_data 文件夹
-          """
+      # - name: run-one-iter-for-llm
+      #   run: |
+      #     ssh ${CAMB_CLUSTER} """
+      #     set -ex
+      #     cd ${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb/dipu
+      #     export PYTORCH_DIR=${CAMB_TORCH_BASE_DIR}/${PYTORCH_COMMIT}
+      #     echo "pytorch dir: \${PYTORCH_DIR}"
+      #     source scripts/ci/camb/ci_camb_env.sh
+      #     basic_path=${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb/dipu/mmlab_pack
+      #     source scripts/ci/ci_one_iter.sh export_pythonpath_camb \${basic_path}
+      #     export PYTHONPATH=\$(pwd):\$PYTHONPATH
+      #     cd mmlab_pack
+      #     rm -rf one_iter_data
+      #     python ../scripts/ci/ci_run_one_iter.py camb ${GITHUB_JOB} "mlu:${MLU_REQUESTS}" \"${CAMB_PARTATION}\" "llm" && rm -rf one_iter_data || (rm -rf one_iter_data && exit 1)
+      #     """
+      # - name: Perform cleanup one iter data
+      #   if: always()
+      #   run: |
+      #     ssh ${CAMB_CLUSTER} """
+      #         set -ex
+      #         echo "${GITHUB_RUN_NUMBER}_${GITHUB_JOB}"
+      #         scancel -n "${GITHUB_RUN_NUMBER}_${GITHUB_JOB}"
+      #         cd ${CAMB_CI_PATH}/${GITHUB_RUN_NUMBER}/Build-Camb/dipu/mmlab_pack
+      #         rm -rf one_iter_data
+      #         touch one_iter_data # 用于占位，防止创建新的 one_iter_data 文件夹
+      #     """
 
       - name: Check for failure
         if: ${{ failure() }}
