add other sco ci

diff --git a/.github/workflows/runs-on-sco.yml b/.github/workflows/runs-on-sco.yml
--- a/.github/workflows/runs-on-sco.yml
+++ b/.github/workflows/runs-on-sco.yml
@@ -19,7 +19,7 @@ on:
 env:
   DEEPLINK_PATH: '/mnt/cache/share/deeplinkci/github/${{ github.repository }}'
   ALL_COVERAGE: ${{ (contains( github.ref, 'main') || startsWith(github.ref, 'refs/heads/v') || startsWith(github.ref, 'refs/heads/dev')) && 'ON' || 'OFF' }}
-  REQUIRE_COVERAGE: ${{ vars.REQUIRE_COVERAGE != '' && vars.REQUIRE_COVERAGE || '40' }}
+  REQUIRE_COVERAGE: ${{ vars.REQUIRE_COVERAGE != '' && vars.REQUIRE_COVERAGE || '0' }}
 
 jobs:
   checkout_code:
@@ -62,6 +62,17 @@ jobs:
           srun --job-name=${GITHUB_JOB} bash -c "export USE_COVERAGE=ON && cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/Build-Cuda/dipu \
           && source /mnt/cache/share/deeplinkci/github/dipu_env  \
           && bash tests/run_nv_tests.sh"
+          if [ "${ALL_COVERAGE}" = "ON" ]; then
+          bash /mnt/cache/share/platform/dep/sonar/coverage_DIPU_nv.sh ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1} ${GITHUB_RUN_NUMBER} || echo "get coverage fail"
+          fi
+      - name: increment coverage check
+        if: ${{ contains( github.event_name, 'pull_request' ) && contains( github.base_ref, 'main' ) }}
+        run: |
+          set -e
+          cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/Build-Cuda
+          ln -s ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source-main/dipu/third_party/DIOPI/scripts scripts
+          source ${ENV_PATH}/pt2.0_diopi
+          bash scripts/increment_coverage.sh ${REQUIRE_COVERAGE}
 
   Test-One-Iter_Cuda:
     name: Test-one-iter-cuda
